const navigationStrings = {
  LOGIN: 'Login',
  HOME_PAGE: 'HomePage',
  ON_BOARDING: 'OnBoarding',
  HOME: 'Home',
  PROFILE: 'Profile',
  EXPLORE: 'Explore',
  POST: 'Post',
  CHAT: 'Chat',
  NOTIFICATION: 'Notification',
  NEWS: 'News',
  POPULAR: 'Popular',
  GAME_DETAIL: 'GameDetail',
  AUTH_CONFIRM: 'AuthConfirm',
  TRAINING: 'Training',
  TRAINING_ITEM: 'TrainingItem',
  DRAWER_STACK: 'DrawerStack',
  LIST_FRIEND: 'ListFriend',
  SETTING: 'Setting',
  SIGN_OUT: 'SignOut',
  POLICY: 'Policy',
  BOOK_MARK: 'BookMark',
  POMO_FOCUS: 'Pomofoucs',
  WebView: 'WebView',
};

const navBarTitle = {
  LOGIN: 'Login',
  HOME_PAGE: 'Home page',
  ON_BOARDING: 'On boarding',
  HOME: 'Home',
  PROFILE: 'Profile',
  EXPLORE: 'Explore',
  POST: 'Post',
  CHAT: 'Chat',
  NOTIFICATION: 'Notification',
  POMOTIMER: 'Pomo timer',
  NEWS: 'News',
  POPULAR: 'Popular',
  GAME_DETAIL: 'Game detail',
  AUTH_CONFIRM: 'Auth confirm',
  TRAINING: 'Training',
  TRAINING_ITEM: 'Training item',
  DRAWER_STACK: 'Drawer stack',
  LIST_FRIEND: 'List friend',
  SETTING: 'Setting',
  SIGN_OUT: 'Sign out',
  POLICY: 'Policy',
  BOOK_MARK: 'Book mark',
  POMO_FOCUS: 'Pomo foucs',
  WebView: 'WebView',
};

export {navigationStrings, navBarTitle};
